// <auto-generated />
namespace Inlämningsupp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class People1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(People1));
        
        string IMigrationMetadata.Id
        {
            get { return "201610260854258_People1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
